version: '3'
services:
  user_management:
    build:
      context: ./accounts
    container_name: accounts
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    depends_on:
      - db

  news_service:
    build:
      context: ./news
    container_name: news
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    depends_on:
      - db

  comment_service:
    build:
      context: ./comments
    container_name: comments
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
